=begin
#KubeVirt API

#This is KubeVirt API an add-on for Kubernetes.

The version of the OpenAPI document: 1.0.0
Contact: kubevirt-dev@googlegroups.com
Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module Kubevirt
  class V1StallDetectorOptions < ApiModelBase
    # CompletionTimeoutFactor multiplies the computed migration completion timeout to determine the total time budget for deciding whether a forced switchover can still finish in time, and to extend the abort deadline after initiating a completion-timeout-driven switchover. Defaults to \"2\".
    attr_accessor :completion_timeout_factor

    # EwmaAlpha is the smoothing factor for the exponentially weighted moving average of observed migration bandwidth. Must be in the range (0, 1]; zero is invalid because the estimate would never incorporate new samples. Higher values weight recent samples more heavily. Defaults to \"0.4\".
    attr_accessor :ewma_alpha

    # PatienceWindowDecayFactor is the factor by which the relaxation patience window is multiplied after each best-remaining-bytes relaxation step. Defaults to \"0.5\".
    attr_accessor :patience_window_decay_factor

    # PrecopyPossibleFactor is the maximum factor by which estimated downtime may exceed MaxDowntime while still attempting a soft stop-and-copy instead of aborting the migration. Defaults to \"1.5\".
    attr_accessor :precopy_possible_factor

    # SearchLocalMinima controls whether convergence actions are delayed until remaining bytes reach a local minimum near the best observed value. When false, actions may trigger as soon as a stall is detected. Defaults to true.
    attr_accessor :search_local_minima

    # StallMargin is the fractional tolerance, expressed as a percentage, used when comparing remaining migration bytes against the best observed value to detect stalls and local minima. A stall is reported when remaining bytes stay above (1 - StallMargin/100) of the outside-window minimum. Defaults to 4.
    attr_accessor :stall_margin

    # StallProgressTimeout is the duration in seconds of the sliding window used to track minimum remaining-bytes and detect when migration progress has stalled. Defaults to 40.
    attr_accessor :stall_progress_timeout

    # SwitchoverTimeout is the duration in seconds allowed for a stop-and-copy or post-copy switchover to complete after being triggered before the migration is aborted. Defaults to 60.
    attr_accessor :switchover_timeout

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'completion_timeout_factor' => :'completionTimeoutFactor',
        :'ewma_alpha' => :'ewmaAlpha',
        :'patience_window_decay_factor' => :'patienceWindowDecayFactor',
        :'precopy_possible_factor' => :'precopyPossibleFactor',
        :'search_local_minima' => :'searchLocalMinima',
        :'stall_margin' => :'stallMargin',
        :'stall_progress_timeout' => :'stallProgressTimeout',
        :'switchover_timeout' => :'switchoverTimeout'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'completion_timeout_factor' => :'String',
        :'ewma_alpha' => :'String',
        :'patience_window_decay_factor' => :'String',
        :'precopy_possible_factor' => :'String',
        :'search_local_minima' => :'Boolean',
        :'stall_margin' => :'Integer',
        :'stall_progress_timeout' => :'Integer',
        :'switchover_timeout' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Kubevirt::V1StallDetectorOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Kubevirt::V1StallDetectorOptions`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'completion_timeout_factor')
        self.completion_timeout_factor = attributes[:'completion_timeout_factor']
      end

      if attributes.key?(:'ewma_alpha')
        self.ewma_alpha = attributes[:'ewma_alpha']
      end

      if attributes.key?(:'patience_window_decay_factor')
        self.patience_window_decay_factor = attributes[:'patience_window_decay_factor']
      end

      if attributes.key?(:'precopy_possible_factor')
        self.precopy_possible_factor = attributes[:'precopy_possible_factor']
      end

      if attributes.key?(:'search_local_minima')
        self.search_local_minima = attributes[:'search_local_minima']
      end

      if attributes.key?(:'stall_margin')
        self.stall_margin = attributes[:'stall_margin']
      end

      if attributes.key?(:'stall_progress_timeout')
        self.stall_progress_timeout = attributes[:'stall_progress_timeout']
      end

      if attributes.key?(:'switchover_timeout')
        self.switchover_timeout = attributes[:'switchover_timeout']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          completion_timeout_factor == o.completion_timeout_factor &&
          ewma_alpha == o.ewma_alpha &&
          patience_window_decay_factor == o.patience_window_decay_factor &&
          precopy_possible_factor == o.precopy_possible_factor &&
          search_local_minima == o.search_local_minima &&
          stall_margin == o.stall_margin &&
          stall_progress_timeout == o.stall_progress_timeout &&
          switchover_timeout == o.switchover_timeout
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [completion_timeout_factor, ewma_alpha, patience_window_decay_factor, precopy_possible_factor, search_local_minima, stall_margin, stall_progress_timeout, switchover_timeout].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
